#
# Edwp-05 : 
#----------------------------------------------

# 1) Get the base image 
#    Hint : use FROM Keyword
#       For Java : java:8 
#       For Python : python:3.6 
#       For Node : node:8.11.4 

# 2) Create a folder called app under /home
#     Hint : user mkdir keyword

# 3) Copy the code from source folder to /home/app/
#    Hint : use COPY keyword

# 4) Change the working directory to /home/app/
#    Hint : use WORKDIR cmd


# 5) Install the dependencies
#    Hint : use RUN keyword
#         For Java:
#         For Python:    
#         For Node: npm install

# 6) Expose the server port (this is for dev reference, EXPOSE cmd will not
#      open up any ports)  
#    Hint : use EXPOSE keyword

# 7) Start the server with Entrypoint
#    Hint : use ENTRYPOINT keyword
#       For Java :
#       For Python :
#       For Node : node server.js

# 8) Create the image  
#   Hint : use docker build

# 9) Run the container and expose the port
#   Hint : use docker run 


