# Edwp-05 : 
#----------------------------------------------

# 1) Get the base image 
#    Hint : use FROM Keyword
#       For Java : 
#       For Python : 
#       For Node : 

# 2) Install the external dependencies (build tool, etc)
#    Hint : use RUN keyword
#      For Java :
#      For Python :
#      For Node : 

# 3) Create a folder called app under /home
#     Hint : user mkdir keyword

# 4) Copy the code from source folder to /home/app/
#    Hint : use COPY keyword

# 5) Change the working directory to /home/app/
#    Hint : use WORKDIR cmd

# 6) Install the dependencies
#    Hint : use RUN keyword
#         For Java:
#         For Python:    
#         For Node:

# 7) Expose the server port (this is for dev reference, EXPOSE cmd will not
#      open up any ports)  
#    Hint : use EXPOSE keyword

# 8) Start the server with Entrypoint
#    Hint : use ENTRYPOINT keyword
#

# 9) Create the image  
#   Hint : use docker build

# 10) Run the container and expose the port
#   Hint : use docker run 


