# edwp-03
#

# 1) Create a base ubuntu 16.04 layer
#    Hint : use FROM

# 2) Create intermediate layer by installing git
#    Hint :apt-get update
#          apt-get install -y git
#

# 3) Create intermediate layer by installing any one

#      a) java 1.8
        # apt-get update
        # apt install openjdk-8-jdk -y

#      b) python 3.6
        # apt-get update
        # apt-get install -y python3

#
#      c) node 8.11.4
  # install curl apt-get install curl -y
	#  curl -sL https://deb.nodesource.com/setup_8.x | bash -
        # apt-get install -y nodejs

# 4) copy hello_world to /home
#    Hint : use copy command

# 5) Create entrypoint to run hello_world
#    Hint : use ENTRYPOINT

# 6) Build an image named "edwp03"

# 7) Create the container and run in daemon mode
#    Hint : use "docker run -d <image name> "

# 8) Inspect the container check the versions for one of
#	the java , python, node
#    Hint : use "docker exec -it <cnt> /bin/bash"
#
