# edwp-03
#------------------------------------

# 1) Create a base ubuntu 16.04 layer
#    Hint : use FROM

# 2) Create intermediate layer by installing git
#    Hint :apt-get update  
#          apt-get install -y git
# 

# 3) Create intermediate layer by installing one of 
# the following 

#      a) java 1.8
        # apt-get update
        # apt install openjdk-8-jdk

#      b) python 3.6
        # apt-get update 
        # apt-get install -y python3.6  
#
#      c) node 8.11.4 (Fix this)
	#  curl -sL https://deb.nodesource.com/setup_8.x | bash -
        # apt-get install -y nodejs
        # apt-get install -y npm

# 3) copy hello_world to /home
#    Hint : use copy command

# 4) Create entrypoint to run hello_world
#    Hint : use ENTRYPOINT
            
# 5) Build an image named "edwp03" 
#    Hint : use "docker <build> .. command
#

# 6) Create the container and run in daemon mode
#    Hint : use "docker run -d <image name> "


# 7) Inspect the container check the versions for one of 
#	the java , python, node
#    Hint : use "docker exec -it <cnt> /bin/bash"
#

