# Edwp-04
#

# 1) Create a base ubuntu 18.04 layer
#    Hint : use FROM

# 2) Create a directory called app at home
#    Hint : mkdir ~/app

# 3) Copy hello_server to /app         
#    Hint : use COPY command

# 4) Expose the port 9000 (this will not acutally open/unblock the port)
#    Hint : use EXPOSE command

# 5) Specify the entry point to start the server
#    Hint : use ENTRYPOINT

# 6) Build the image dwp-04
#    Hint : docker build -t <name> .

# 7) Run two containers

# 3) Create inermediate layer by installing one  

#      a) java 1.8
        # apt-get update
        # apt install openjdk-8-jdk

#      b) python 3.6
        # apt-get update 
        # apt-get install -y python3.6  
#
#      c) node 8.11.4 (Fix this)
	# curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
        # apt-get install -y nodejs
                 
# 3) Build an image named "dwp01" 
#    Hint : use "docker <build> .. command
#


# 4) Create the container and run in daemon mode
#    Hint : use "docker run -d <image name> "
#


# 5) Inspect the container check the versions for one of 
#	the java , python, node
#    Hint : use "docker exec -it <cnt> /bin/bash"
#

