#Edwp-02

# 1) set base image layer from ubuntu 16.04
#  Hint : use FROM keyword

# 2) COPY "hello_world" binary to /home/ directory
# Hint : use COPY <src> <dest>

# 3) Change workdir to /home/
# Hint : use WORKDIR

# 4) set entrypoint for running the process
# Hint : use ENTTRYPOINT

# 5) Build the image with the name "dwp02"
# Hint : "docker build ...." 

# 6) Create a container using  dwp02 image
# Hint : "docker run ..."

# 7) Run docker in daemon mode
# Hint : use "-d" option of "docker run"

# 8) Check the status of the container
# Hint : "docker ps"
