#Edwp-02

# 1) set base image layer from ubuntu 18.04
#  Hint : use FROM keyword
FROM ubuntu:18.04
# 2) COPY "hello_world" binary to /home/ directory
# Hint : use COPY <src> <dest>
COPY ./hello_world /home/
# 3) Change workdir to /home/
# Hint : use WORKDIR
WORKDIR /home/
# 4) set entrypoint for running the process
# Hint : use ENTTRYPOINT
ENTRYPOINT ["./hello_world"]
# 5) Build the image with the name "dwp02"
# Hint : "docker build ...." 

# 6) Create a container using  dwp02 image
# Hint : "docker run ..."

# 7) Run docker in daemon mode
# Hint : use "-d" option of "docker run"

# 8) Check the status of the container
# Hint : "docker ps"
