# Solution to dwp-01

# 1) use FROM and COPY
FROM scratch
COPY hello_word /

# 2) Use ubuntu 18.04 as base image
FROM ubuntu:18.04

# 3) Run the command "docker build -t dwp01 ."

# 4) use RUN(shell form) with pwd shell command
RUN pwd

# 5) list all the directories in the current 
# working directory, use exec form

RUN ["ls", "-l"]

