# Edwp-01
#
# 1) Create a base image and copy hello_world 
#    Hint : use FROM and COPY keywords 
#FROM scratch

# 2) Create a base ubuntu 18.04 layer
#    Hint : use FROM
FROM ubuntu:18.04
COPY ./hello_world /
#
# 3) Build an image named "dwp01" 
#    Hint : use "docker <build> .. command
#
# 4) Print the current working directory 
#    Hint : use "pwd" shell/console command
#
# 5) List all the files in the current working directory
#    Hint : use ls command to list the files


